---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Mark change request cloded
      servicenow.itsm.change_request:
        number: "{{ change_number }}"
        state: closed
      register: change
 