---
- name: Play to create ServiceNow Incident
  hosts: localhost

  tasks:
  - name: Create Incident 
    servicenow.itsm.incident:
      caller: admin
      state: new
      short_description: "{{ short_description }}"
      description: "{{ detailed_description }}"
      category: "{{ category }}"
      impact: "{{ impact }}"
      urgency: "{{ urgency }}"
    register: incident
