---
- name: Play to create ServiceNow Incident
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create Incident 
    servicenow.itsm.incident:
      caller: admin
      state: new
      short_description: Test Manual Incident Creation on Operating Software Category
      impact: low
      urgency: low
      other:
        category: Software
        subcategory: Operating System
        cmdb_ci: RHEL8-4    
    register: incident_number
  - debug: 
      var: incident_number