---
- name: Play to create ServiceNow Incident
  hosts: localhost

  tasks:
  - name: Create Incident 
    servicenow.itsm.incident:
      caller: admin
      state: new
      short_description: Demo incident RHUG 2
      impact: low
      urgency: low
    register: incident
