---
- name: Demonstrate CMDB CI Creation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create CI for light 1
      ansible.builtin.set_fact:
        instance:
          name: 1001-lumiere-2
          fqdn: 1001-lumiere-2.rhcasalab.com
          public_ip_address: 0.0.0.0
          status : pending_install
          category : To be scan
          environment : production
          operational_status: operational
          os : Linux Red Hat
          attributes: 233


    - name: Register the newly-created Server instance
      servicenow.itsm.configuration_item:
        name: "{{ instance.name }}"
        sys_class_name: cmdb_ci_linux_server
        category : "{{ instance.category }}"
        install_status: "{{ instance.status }}"
        ip_address: "{{ instance.public_ip_address }}"
        operational_status: "{{ instance.operational_status }}"
        other:
          os: "{{ instance.os }}"
          fqdn: "{{ instance.fqdn }}"
          dns_domain: "{{ instance.fqdn }}"
          host_name: "{{ instance.fqdn }}"
          attributes: "{{ instance.attributes }}"