---
- name: "Disable SELinux"
  gather_facts: no
  hosts: all
  become: yes
  tasks:

  - name: Disable SELinux
    ansible.posix.selinux:
      state: disabled
    register: selinux_status

  - debug:
      var: selinux_status
