---
- name: "Enable SELinux"
  gather_facts: no
  hosts: all
  become: yes
  tasks:

  - name: Enable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: enforcing
    register: selinux_status
  
  - name: Reboot Server
    reboot:
      msg: "Reboot initiated by Ansible for SELinux Enabling"
      connect_timeout: 15
      reboot_timeout: 300      
      test_command: uptime

  - debug:
      var: selinux_status
