---
- name: "Enable SELinux"
  gather_facts: no
  hosts: all
  become: yes
  tasks:

  - name: Enable SELinux
    ansible.posix.selinux:
      policy: targeted
      state: enforcing
    register: selinux_status

  - set_stats:
      data:
        c_hostname: "{{ inventory_hostname }}"

  - debug:
      var: selinux_status
