---
- name: Retired a CI from CMDB
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Update Server state
      servicenow.itsm.configuration_item:
        sys_id: e1dc69d11b21011082f18515ec4bcb2c
        install_status: retired
        operational_status: retired