---
- name: "Send slack message"
  gather_facts: no
  hosts: localhost
  become: yes
  tasks:
  - name: "Send slack message"
    community.general.slack:
      token: T01DW2WQ2NM/B01LEJL8P60/ZlCoRFrR6oL6Mk2njcDVyFMX
      msg: "{{ message }}"
    become: no
    check_mode: no
    run_once: yes
