---
- name: Demonstrate CMDB management
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create VM CI in CMDB
      ansible.builtin.set_fact:
        instance:
          name: "{{ vm_name }}"
          id: vm1234567890
          public_ip_address: "{{ ansible_host }}"      

    - name: Register the newly-created VM instance
      servicenow.itsm.configuration_item:
        name: "{{ instance.name }}"
        sys_class_name: cmdb_ci_vm_instance
        ip_address: "{{ instance.public_ip_address }}"
        other:
          vm_inst_id: "{{ instance.id }}"